# Description: Configuration file for training and testing

model_name: "unet_nods_nobottle_ourkernel"
model_type: "unet"
dimension: 2
in_channels: 4
out_channels: 3
kernels: [32, 64, 128, 256, 512] # 64, 96, 128, 192, 256, 384, 512 # 32, 64, 128, 256, 512
batch_size: 4
epochs: 40
learning_rate: 0.0003
deep_supervision: False
deep_supervision_head: 2
instance_norm: True
activation: "leakyrelu"
focal: True
n_bottleneck: 0
device: "cuda:2"
weight_decay: 0
results_dir: "results2"
overwrite: False
amp: False

# dont change
data: "/auto/data2/myilmaz/DL_Project/BraTS2021_Preprocessed/11_3d_2"
test_data: "/auto/data2/myilmaz/DL_Project/BraTS2021_test"
brats: True
fold: 0
gpus: 1
task: 11
num_workers: 16
nfolds: 5