model_name: "my_model_Att_ourbest_kernels"
model_type: "attunet"
dimension: 3
in_channels: 4
out_channels: 3
kernels: [32, 64, 128, 256, 512] # 64, 96, 128, 192, 256, 384, 512 # 32, 64, 128, 256, 512
batch_size: 4
epochs: 70
learning_rate: 0.0003
deep_supervision: True
deep_supervision_head: 2
instance_norm: True
activation: "leakyrelu"
focal: True
device: "cuda:0"
weight_decay: 0
results_dir: "results2"
overwrite: False
delete_prev_ckpts: False
